---

- hosts: all
  become: true
  tasks:

  - name: install bind9 and apache2 and also update apt packages
    apt:
      name:
        - "{{ my_love }}"
        - bind9
      state: latest
      update_cache: yes
