---

- hosts: all
  become: true
  tasks:

  - name: install bind9 and apache2 and also update apt packages
    package:
      name:
        - "{{ my_love }}"
        - bind9
        - php
      state: latest
  - name: update apt pack
    package:
      update_cache: yes

